Arcade/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include("home.urls")),
    path('features/', include("features.urls")),
    path('menu/', include("menu.urls")),
    path('bundles/', include("bundles.urls")),
    path("accounts/", include("allauth.urls")),
    path("booking/", include("booking.urls", namespace='booking')),
    path("myaccount/", include("myaccount.urls")),
]

booking/urls.py
from django.urls import path
from . import views


app_name = 'booking'

urlpatterns = [
    path('', views.booking_view, name='booking'),
    path('confirmation/<int:booking_id>/', views.booking_confirmation, name='booking_confirmation'),
]

home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home')
]

menu/urls.py
from django.urls import path
from .views import menu_items_api, menu

urlpatterns = [
    path('', menu, name='menu'),
    path('api/menu-items/', menu_items_api, name='menu-items-api'),
    path('api/menu-items/<int:category_id>/', menu_items_api, name='menu-items-api'),
]

myaccount/urls.py
from django.urls import path
from . import views

app_name = 'myaccount'

urlpatterns = [
    path('', views.myaccount_view, name='myaccount'),
    path('edit/<int:booking_id>/', views.edit_booking_view, name='edit_booking'),
]

booking/models.py
from django.db import models
from bundles.models import Bundle
from django.contrib.auth.models import User
from django.utils import timezone

class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bundle = models.ForeignKey(Bundle, on_delete=models.SET_NULL, null=True, blank=True)
    date = models.DateField(default=timezone.localdate)
    time = models.TimeField(default=timezone.localtime)

    def __str__(self):
        return f"{self.bundle} - {self.date} at {self.time}"

bundles/models.py
from django.db import models
from menu.models import Category, MenuItem

class Bundle(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    food_categories = models.ManyToManyField(Category, related_name='food_bundle', limit_choices_to={'type': 'food'}, blank=True)
    drink_categories = models.ManyToManyField(Category, related_name='drink_bundle', limit_choices_to={'type': 'drink'}, blank=True)
    number_of_people = models.IntegerField(default=1)
    playtime_hours = models.DecimalField(max_digits=4, decimal_places=2, default=0.0)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)

    def __str__(self):
        return self.name

home/models.py
from django.db import models


# Create your models here.

    

menu/models.py
from django.db import models

def create_default_category():
    category, _ = Category.objects.get_or_create(name='Default Category')
    return category.pk

class Category(models.Model):
    CATEGORY_TYPES = (
        ('food', 'Food'),
        ('drink', 'Drink'),
    )
    name = models.CharField(max_length=100)
    token_cost = models.IntegerField(default=1, help_text="Token cost for each item in this category")
    type = models.CharField(max_length=5, choices=CATEGORY_TYPES, default='food', help_text='Specify whether this category is for food or drink.')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

class MenuItem(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    category = models.ForeignKey(Category, related_name='menuitems', on_delete=models.CASCADE, default=create_default_category)

    def __str__(self):
        return self.name

class MenuItemOption(models.Model):
    menu_item = models.ForeignKey(MenuItem, related_name='options', on_delete=models.CASCADE)
    size = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f"{self.menu_item.name} - {self.size} - £{self.price}"

booking/forms.py
from django import forms
from .models import Booking
from bundles.models import Bundle
from django.utils import timezone

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['bundle', 'date', 'time']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'time': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control', 'step': '60'})
        }

    def __init__(self, *args, **kwargs):
        super(BookingForm, self).__init__(*args, **kwargs)
        if not self.instance.pk:
            self.fields['date'].initial = timezone.localdate()
        self.fields['bundle'].queryset = Bundle.objects.all()

    def clean_date(self):
        date = self.cleaned_data.get('date')
        if date:
            today = timezone.localdate()
            if date <= today:
                raise ValidationError("Bookings cannot be made for today. Please select a future date.")
        return date

    def clean_time(self):
        time = self.cleaned_data.get('time')
        if time:
            opening_time = timezone.datetime.strptime("09:00", "%H:%M").time()
            closing_time = timezone.datetime.strptime("22:00", "%H:%M").time()
            if not (opening_time <= time <= closing_time):
                raise ValidationError("Bookings can only be made between 9 AM and 10 PM.")
            time = time.replace(second=0, microsecond=0)
        return time

    def clean_bundle(self):
        bundle = self.cleaned_data.get('bundle')
        if bundle and not Bundle.objects.filter(id=bundle.id).exists():
            raise ValidationError("The selected bundle does not exist.")
        return bundle

bundles/forms.py
from django import forms
from .models import Bundle, Category, Drink

class BundleForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(queryset=Category.objects.all(), widget=forms.CheckboxSelectMultiple)
    drinks = forms.ModelMultipleChoiceField(queryset=Drink.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Bundle
        fields = ['name', 'food_tokens', 'drink_tokens', 'categories', 'drinks', 'number_of_people', 'playtime_hours', 'price']

menu/forms.py
from django import forms
from .models import MenuItemOption

class MenuItemOptionForm(forms.ModelForm):
    class Meta:
        model = MenuItemOption
        fields = '__all__'
        widgets = {
            'size': forms.TextInput(attrs={'placeholder': 'Optional if only one size'}),
        }
    
    def __init__(self, *args, **kwargs):
        super(MenuItemOptionForm, self).__init__(*args, **kwargs)
        self.fields['size'].required = False

booking/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import BookingForm
from .models import Booking
from bundles.models import Bundle
import logging

logger = logging.getLogger(__name__)

@login_required
def booking_view(request):
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.user = request.user
            booking.save()
            return redirect('booking:booking_confirmation', booking_id=booking.id)
        else:
            logger.error(f"Form errors: {form.errors}")
    else:
        bundle_id = request.GET.get('bundle')
        initial_data = {}
        if bundle_id:
            try:
                bundle = Bundle.objects.get(id=bundle_id)
                initial_data['bundle'] = bundle
            except Bundle.DoesNotExist:
                logger.error(f"Bundle with id {bundle_id} does not exist.")
                initial_data['bundle'] = None
        
        form = BookingForm(initial=initial_data)

    return render(request, 'booking.html', {'form': form})

@login_required
def booking_confirmation(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    return render(request, 'booking_confirmation.html', {'booking': booking})

bundles/views.py
from django.shortcuts import render
from .models import Bundle
from menu.models import MenuItem
from django.http import JsonResponse

# Create your views here. 
def bundles(request):
    bundles = Bundle.objects.prefetch_related('food_categories', 'drink_categories').all()
    return render(request, "bundles.html", {'bundles': bundles})

def bundle_list(request):
    bundles = Bundle.objects.all()
    bundles_data = [{
        'id': bundle.id,
        'name': bundle.name,
        'description': bundle.description,
    } for bundle in bundles]
    
    return JsonResponse({'bundles': bundles_data})

def bundle_detail(request, pk):
    try:
        bundle = Bundle.objects.get(pk=pk)
        food_category_ids = bundle.food_categories.values_list('id', flat=True)
        drink_category_ids = bundle.drink_categories.values_list('id', flat=True)
        food_items = MenuItem.objects.filter(category__in=food_category_ids)
        drink_items = MenuItem.objects.filter(category__in=drink_category_ids)
        response = {
            "id": bundle.id,
            "food_categories": [{"id": cat.id, "name": cat.name} for cat in bundle.food_categories.all()],
            "drink_categories": [{"id": cat.id, "name": cat.name} for cat in bundle.drink_categories.all()],
            "food_items": [{"id": item.id, "name": item.name, "category_id": item.category_id} for item in food_items],
            "drink_items": [{"id": item.id, "name": item.name, "category_id": item.category_id} for item in drink_items],
        }
        return JsonResponse(response)
    except Bundle.DoesNotExist:
        return JsonResponse({'error': 'Bundle not found'}, status=404)

features/views.py
from django.shortcuts import render

# Create your views here.
def features(request):
    template_name = "features.html"
    return render(request, template_name)

home/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    template_name = "home.html"
    return render(request, template_name)

menu/views.py
from django.shortcuts import render
from .models import Category, MenuItem
from django.http import JsonResponse

def menu(request):
    categories = Category.objects.exclude(name='Default Category').prefetch_related('menuitems__options')
    return render(request, 'menu.html', {'categories': categories})

def menu_items_api(request, category_id=None):
    if category_id:
        
        menu_items = MenuItem.objects.filter(category_id=category_id).select_related('category')
    else:
        menu_items = MenuItem.objects.all().select_related('category')
    
    items = [
        {
            "id": item.id, 
            "name": item.name, 
            "token_cost": item.category.token_cost,
        } 
        for item in menu_items
    ]
    return JsonResponse({"menu_items": items})

templates/account.html
{% extends 'base.html' %}
{% block content %}
<section class="container">
    <h2>My Account</h2>
    <h3>My Bookings</h3>
    {% if messages %}
        <div class="alert-container">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <table class="table">
        <thead>
            <tr>
                <th>Bundle</th>
                <th>Date</th>
                <th>Time</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for booking in user_bookings %}
            <tr>
                <td>{{ booking.bundle }}</td>
                <td>{{ booking.date }}</td>
                <td>{{ booking.time }}</td>
                <td>
                    <form method="post" action="{% url 'myaccount:edit_booking' booking.id %}" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </form>
                    <form method="post" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="booking_id" value="{{ booking.id }}">
                        <button type="submit" name="cancel_booking" class="btn btn-danger" onclick="return confirm('Are you sure you want to cancel this booking?');">Cancel</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
{% endblock %}

templates/base.html
{% load static %}
{% url 'home' as home_url %}
{% url 'features' as features_url %}
{% url 'menu' as menu_url %}
{% url 'bundles' as bundles_url %}
{% url 'booking:booking' as booking_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}
{% url 'myaccount:myaccount' as myaccount_url %}

<!DOCTYPE html>
<html class="h-100" lang="en">
<head>
    <!-- Meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Website for fans of retro arcades, with ability to book a time and date for your visit">
    
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- Additional Links -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Back To The Arcade (again)</title>
</head>
<body>
  
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static '/images/BTTAlogo.png' %}" alt="Logo" style="height: 40px;">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link {% if request.path == home_url %}active{% endif %}" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == features_url %}active{% endif %}" href="{% url 'features' %}">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == menu_url %}active{% endif %}" href="{% url 'menu' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == bundles_url %}active{% endif %}" href="{% url 'bundles' %}">Bundles</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == booking_url %}active{% endif %}" href="{% url 'booking:booking' %}">Book Now</a>
              </li>
            </ul>
            <ul class="nav navbar-nav ms-auto">
              {% if user.is_authenticated %}            
              <li class="nav-item">
                <span class="navbar-text">Logged in as: </span>
                <a href="{% url 'myaccount:myaccount' %}">{{ user.username }}</a>
              </li> 
              <li class="nav-item">
                <a class="nav-link {% if request.path == logout_url %}active{% endif %}" href="{% url 'account_logout' %}">Logout</a>
              </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path == signup_url %}active{% endif %}" href="{% url 'account_signup' %}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == login_url %}active{% endif %}" href="{% url 'account_login' %}">Login</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

      <main class="flex-shrink-0 main-bg">
      

        {% block content %}

        {% endblock content %}

      </main>

      <footer class="footer mt-auto py-3 bg-dark">
        <ul id="social-networks">
            <li><a href="https://www.facebook.com" target="_blank" rel="noopener" aria-label="Visit our Facebook page (opens in a new tab)"><i class="fa-brands fa-facebook"></i></a></li>
            <li><a href="https://www.twitter.com" target="_blank" rel="noopener" aria-label="Visit our Twitter profile (opens in a new tab)"><i class="fa-brands fa-twitter"></i></a></li>
            <li><a href="https://www.YouTube.com" target="_blank" rel="noopener" aria-label="Visit our YouTube channel (opens in a new tab)"><i class="fa-brands fa-youtube"></i></a></li>
            <li><a href="https://www.instagram.com" target="_blank" rel="noopener" aria-label="Visit our Instagram page (opens in a new tab)"><i class="fa-brands fa-instagram"></i></a></li>
          </ul>
      </footer>

      <script src="https://kit.fontawesome.com/706cded973.js" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
        </script>
      
</body>
</html>

templates/booking.html
{% extends 'base.html' %}
{% load static %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% block content %}

    <section class="container-fluid">
        <div class="row">
            <div id="booking" class="col-12 bg-img-container">
                <div class="cover-text">
                    <h2>Book Your Visit Now!</h2>
                    <h3>Choose the bundle that meets your needs</h3>
                </div>
            </div>
        </div>
    </section>
    
    <section class="container-fluid end">
        <div class="row justify-content-center">
            <div class="col-12">
                <h2>Booking your Visit</h2>
                <h3>Choose from our bundles,
                    <br>Pick a time and date that suits you,
                    <br>We look forward to seeing you soon!</h3>
                <h4>Open 7 Days a Week, between 09:00 - 22:00</h4>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% if user.is_authenticated %}
        <form method="post" id="booking-form">
            {% csrf_token %}
            
            <div class="form-group">
                {{ form.bundle.label_tag }} {{ form.bundle }}
            </div>
    
            
            <div class="form-group">
                {{ form.date.label_tag }} {{ form.date }}
                {{ form.time.label_tag }} {{ form.time }}
            </div>
            
            {% if form.errors %}
            <div class="error-messages">
            <p>Please correct the following errors:</p>
            <ul>
                {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <li><strong>{{ field.label }}:</strong> {{ error }}</li>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        
{% endif %}
<button type="submit" class="btn btn-warning">Submit Booking</button>
        </form>
        {% else %}
        <p>Please <a href="{% url 'account_login' %}?next={{ request.path }}">sign in</a> or <a href="{% url 'account_signup' %}">register</a> to make a booking.</p>
        {% endif %}
            </div>
        </div>
    </section>
        
{% endblock %}

templates/booking_confirmation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="container-fluid" style="padding-top: 70px;">
    <div class="row">
        <div class="col-md-12">
            <h2>Booking Confirmation</h2>
            <p>Thank You for your booking!</p>
            <p><strong>Bundle:</strong> {{ booking.bundle.name }}</p>
            <p><strong>Date:</strong> {{ booking.date }}</p>
            <p><strong>Time:</strong> {{ booking.time }}</p>
        </div>
    </div>
</section>


{% endblock %}

templates/bundles.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="container-fluid">
    <div class="row">
        <div id="bundles" class="col-12 bg-img-container">
            <div class="cover-text">
                <h2>Bundles</h2>
                <h3>A selection of bundles for everyone to enjoy</h3>
            </div>
        </div>
    </div>
</section>

<section class="description">
    <div>
        <h2>What are the Costs?</h2>
        <p>Each of our machines can be used pay per play with coins or contactless,<br> And drinks and food can be purchased individually.<br> Pricing for these can be found on the refreshments menu.</p>
    </div>
</section>   

<section class="container-fluid">
    

    {% for bundle in bundles %}
<div class="row justify-content-center">
    <div class="col-lg-8">
        <table class="table">
            <tr>
                <th>Name</th>
                <td>{{ bundle.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ bundle.description | safe }}</td>
            </tr>
            <tr>
                <th>Number of People</th>
                <td>{{ bundle.number_of_people }}</td>
            </tr>
            <tr>
                <th>Playtime Hours</th>
                <td>{{ bundle.playtime_hours }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>£{{ bundle.price }}</td>
            </tr>
        </table>
    </div>
</div>
    <div class="divider">
        <span class="dash"></span>
        <span class="dash"></span>
        <span class="dash"></span>
    </div>
{% endfor %}
</div>
</section>
<section class="container-fluid">
    <div class="row">
      <h2>Ready To Plan Your Visit?</h2>
      <p><a href="{% url 'booking:booking' %}" class="btn btn-warning">Book Now!</a></p>
    </div>
  </section>

{% endblock %}

templates/edit_booking.html
{% extends 'base.html' %}
{% block content %}
<section class="container">
    <h2>Edit Booking</h2>
    {% if messages %}
        <div class="alert-container">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.bundle.label_tag }}
            {{ form.bundle }}
        </div>
        <div class="form-group">
            {{ form.date.label_tag }}
            {{ form.date }}
        </div>
        <div class="form-group">
            {{ form.time.label_tag }}
            {{ form.time }}
        </div>
        {% if form.errors %}
        <div class="alert alert-danger">
            <p>Please correct the following errors:</p>
            <ul>
                {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <li><strong>{{ field.label }}:</strong> {{ error }}</li>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <button type="submit" class="btn btn-success">Save Changes</button>
        <a href="{% url 'myaccount:myaccount' %}" class="btn btn-secondary">Cancel</a>
    </form>
</section>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var existingDate = '{{ booking.date|date:"Y-m-d" }}';
        var existingTime = '{{ booking.time|date:"H:i" }}';
        var existingBundleId = '{{ booking.bundle.id_bundle }}';

        console.log('Date:', existingDate);
        console.log('Time:', existingTime);
        console.log('Bundle ID:', existingBundleId);

        var dateField = document.getElementById('id_date');
        var timeField = document.getElementById('id_time');
        var bundleField = document.getElementById('id_bundle');

        if (dateField) {
            dateField.value = existingDate;
        }

        if (timeField) {
            timeField.value = existingTime;
        }

        if (bundleField) {
            var options = bundleField.options;
            for (var i = 0; i < options.length; i++) {
                if (options[i].value === existingBundleId) {
                    options[i].selected = true;
                    break;
                }
            }
        }
    });
</script>

{% endblock %}

templates/features.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

        <section class="container-fluid">
        <div class="row">
            <div id="features" class="col-12 bg-img-container">
            <div class="cover-text">
                <h2>Features</h2>
                <h3>A wide selection available for everyone</h3>
            </div>
        </div>
        </div>
        </section>
        <section class="container-fluid">
            <h2>What Games are available?</h2>
            <div class="row justify-content-center">   
                <div class="col-md-4 left-text">
                    <div>
                        <h3>Retro Games</h3>
                        <p>We have a wide selection of Retro Arcade dating back as far as the 70's<br>Some of these include:</p>
                        <ul>
                            <li>Space Invaders</li>
                            <li>Pac-Man</li>
                            <li>Golden Axe</li>
                            <li>Street Fighter</li>
                            <li>Donkey Kong</li>
                            <li>Mario Bros</li>
                            <li>Ghosts 'n Goblins</li>
                            <li>Dragons Lair</li>
                        </ul>
                        <p>And many more games available, come and see us for our full range!</p>
                    </div>
                </div>
                <div class="col-md-3 lower-img">
                    <img class="lower-img" src="{% static 'images/girlInArcade.jpg' %}" alt="Space Invaders Logo">
                </div>
                <div class="col-md-4 right-text">
                <div>
                    <h3>Modern Consoles</h3>
                    <p>We also have a selection of modern consoles<br>Some of these include:</p>
                    <ul>
                        <li>PlayStation</li>
                        <li>Playstation 2</li>
                        <li>Playstation 3</li>
                        <li>Sega Megadrive</li>
                        <li>Sega Dreamcast</li>
                        <li>Nintendo 64</li>
                        <li>Nintendo GameCube</li>
                        <li>Nintendo Wii</li>
                        <li>Xbox 360</li>
                    </ul>
                    <p>All of these consoles are packed full of games that can have from 1 to 4 players</p>
                </div>
            </div>
        </div>
        </section>
        <div class="divider">
            <span class="dash"></span>
            <span class="dash"></span>
            <span class="dash"></span>
        </div>
        <section id="options" class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-9">    
                    <h2>Looking for More?</h2>
                    <p>As well as a wide selection of video games and consoles, we also have a vast choice of boardgames and cardgames available.<br>You can also hire a table for tabletop gaming, feel free to bring your own games and come hang out with us!</p>
                </div>
            </div>
        </section>
{% endblock content %}

templates/menu.html
{% extends 'base.html' %} 
{% load static %}
{% url 'booking' as booking_url %}
{% block content %}
<section class="container-fluid">
  <div class="row">
    <div id="menu" class="col-12 bg-img-container">
      <div class="cover-text">
        <h2>Back to the Refreshments</h2>
        <h3>Little Energy Boosters while you're gaming</h3>
      </div>
    </div>
  </div>
</section>
<section class="description">
  <div>
    <div>
      <h2 class="subtitle">Menu Overview</h2>
      <p>
        We have an in-house canteen that offers a selection of tasty treats to
        sustain you during your gaming sessions, with vegan options available on
        request.
      </p>
    </div>
  </div>
</section>
<section class="container-fluid">

    {% for category in categories %}
    <div class="row justify-content-center">
    <div class="col-lg-8">
    <h2>{{ category.name }}</h2>
    <div>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        {% for item in category.menuitems.all %}
        <tr>
          <td>{{ item.name }}</td>
          <td>{{ item.description|default:"N/A"|safe }}</td>
          <td>
            {% if item.options.all.count > 1 %}
              {% for option in item.options.all %}
                {{ option.size }} £{{ option.price }}<br>
              {% endfor %}
            {% else %}
              £{{ item.options.all.first.price }}
            {% endif %}
          </td>
          
        </tr>
        {% empty %}
        <tr>
          <td colspan="3">No menu items available</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="divider">
      <span class="dash"></span>
      <span class="dash"></span>
      <span class="dash"></span>
  </div>
  </div>
  </div>
    {% empty %}
    <p>No categories available</p>
    {% endfor %}
  </div>
</section>
<section class="container-fluid">
  <div class="row">
    <h2>Tickling your tastebuds?</h2>
    <p><a href="{% url 'booking:booking' %}" class="btn btn-warning">Book Now!</a></p>
  </div>
</section>

{% endblock content %}